# The transformer factory set to Xalan, in order to call Java methods
javax.xml.transform.TransformerFactory=org.apache.xalan.processor.TransformerFactoryImpl
org.xml.sax.driver=org.apache.xerces.parsers.SAXParser

# An optional root path replacement (e.g. /home/stagyrite/boringcms/src/main/webapp)
boringcms.base.path=

