hibernate.c3p0.idle_test_period=3000
hibernate.c3p0.max_size=100
hibernate.c3p0.max_statements=50
hibernate.c3p0.min_size=5
hibernate.c3p0.timeout=300
hibernate.cache.region.factory_class=org.hibernate.cache.jcache.JCacheRegionFactory
hibernate.cache.use_query_cache=true
hibernate.cache.use_second_level_cache=true
hibernate.connection.driver_class=org.postgresql.Driver
hibernate.connection.password=2a57606710
hibernate.connection.url=jdbc:postgresql://localhost/boringcms
hibernate.connection.username=boringcms
hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
hibernate.format_sql=true
hibernate.javax.cache.missing_cache_strategy=create
hibernate.javax.cache.provider=org.ehcache.jsr107.EhcacheCachingProvider
hibernate.show_sql=true
